### PR TITLE
neighbor spelling (assuming we're sticking to American spelling!)

### PR DESCRIPTION
**Pull request by Ormorod**

### CODE REVIEW

**Comment by lukashergt** [comment]
Or `neighbour`? ;)

**Comment by williamjameshandley** [comment]
Can we go with the english spelling, and could you make this part of #87?

**Comment by Ormorod** [comment]
but, but, an~~a~~esthetic 🤯

**Comment by williamjameshandley** [comment]
I'm pretty explicit about this in the anesthetic [README](https://github.com/williamjameshandley/anesthetic#whats-in-a-name)!

**Pull request closed without merging**
