### PR TITLE
Pyproject

### LINKED ISSUE #26: build requires numpy
Since you require numpy to be installed in an environment _before_ running `setup.py`, could you include `pyproject.toml` and have a section:

```
[build-system]
requires = ["numpy"]
```

This will enable `pypolychord` to be built without first manually installing numpy (very useful for some CI builds).

### PR DESCRIPTION
**Pull request by steven-murray**
Adds `pyproject.toml` which should de-necessitate pre-installing numpy into a fresh environment before installing `pypolychord`.

Closes #26

### CODE REVIEW

**Comment by steven-murray** [comment]
I think the problem here is that `python setup.py install` doesn't use the `pyproject.yaml`. I updated to use `pip install .` instead -- let's see if that works.

**Comment by steven-murray** [comment]
I think there's something going on here that I don't understand. Could you look at the travis errors? It's picking up the numpy requirement fine, and installing pypolychord fine, but when trying to import it, it's saying that it can't find the shared lib.

**Comment by williamjameshandley** [comment]
Ah, pip installing polychord is currently an open PR #24 Do you have to use pip to get the `.toml` file to work?

**Comment by steven-murray** [comment]
Hmmm yes I think so. I'll have a bit more of a look.

**Comment by steven-murray** [comment]
Yes, using `python setup.py install` of course literally just loads `setup.py` with python, and so will break if `numpy` is not installed. `pip` instead first checks `pyproject.toml` for build deps. Perhaps this PR should just sit until #24 is merged. Is that happening soon?

**Comment by williamjameshandley** [comment]
@tilmantroester, what remains to be done to fix #24 ?

**Comment by tilmantroester** [comment]
Fixing the macOS travis builds and re-adding python 2 support. The travis failure is bizarre while the python 2 part should be straightforward to implement but I haven't had time to look into it.

**Comment by williamjameshandley** [comment]
Hi @steven-murray. There have been some fairly major changes here to the python setup after the merge of #24, and a few new errors are emerging now on the travis build. Have you seen these before in your experience of implementing toml files?

**Comment by steven-murray** [comment]
Wow, no I've never seen errors like that. Looks like it's mostly working with MPI=1, but not with MPI=0. You might have to install some blas library manually?

**Pull request closed without merging**
